Repository dpommerole/POC-Mission-template-generator-front, pull requests merged in 2019-08, with the labels that each got.

#6 Chore/fix project configuration and linter
  .babelrc
  .circleci/config.yml
  .eslintrc.js
  .gitignore
  README.md
  assets/README.md
  components/Logo.vue
  components/README.md
  jest.config.js
  layouts/README.md
  layouts/default.vue
  middleware/README.md
  nuxt.config.js
  package-lock.json
  package.json
  pages/README.md
  pages/index.vue
  plugins/README.md
  static/README.md
  static/favicon.ico
  store/README.md
  test/Logo.spec.js
  yarn.lock
Labels: Ready

#8 feat: add connection page
  nuxt.config.js
  package-lock.json
  package.json
  pages/index.vue
  plugins/vuelidate.js
  store/index.js
Labels: WIP

#9 feat: add inscription page
  pages/index.vue
  pages/signin.vue
  pages/style.css
Labels: Ready

#10 Fit add content
  pages/home.vue
  services/backend.service.js
Labels: Ready

#11 add new mission page
  nuxt.config.js
  package-lock.json
  package.json
  pages/new-mission.vue
  plugins/dragable.js
  plugins/vue-select.js
Labels: Ready

#15 chore: login refacto
  pages/index.vue
  pages/signin.vue
  services/login.service.js
Labels: Ready

#13 Fit add content
  nuxt.config.js
  package-lock.json
  package.json
  pages/index.vue
  pages/mission.vue
  plugins/jspdf.js
  plugins/key.js
  store/utils.js
Labels: Ready

#17 feat: add environment page
  components/modals/modalDeleteEnvironment.vue
  components/modals/modalEditEnvironment.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/environment.vue
  plugins/modal.js
Labels: Ready

#16 chore: add config for env && test
  .env.example
  .gitignore
  nuxt.config.js
  package-lock.json
  package.json
  services/login.service.js
  store/empty.store.js
  store/index.js
  test/services/login.service.spec.js
  yarn.lock
Labels: Ready

#18 MEP
  .env.example
  .gitignore
  components/modals/modalDeleteEnvironment.vue
  components/modals/modalEditEnvironment.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/environment.vue
  pages/home.vue
  pages/index.vue
  pages/mission.vue
  pages/new-mission.vue
  pages/signin.vue
  plugins/dragable.js
  plugins/jspdf.js
  plugins/key.js
  plugins/modal.js
  plugins/vue-select.js
  plugins/vuelidate.js
  services/backend.service.js
  services/login.service.js
  store/empty.store.js
  store/index.js
  store/utils.js
  style/login_signin.css
  test/services/login.service.spec.js
  yarn.lock
Labels: Ready

#19 Chore/add pre commit config
  components/Logo.vue
  package-lock.json
  package.json
  test/Logo.spec.js
  test/services/login.service.spec.js
Labels: Ready, Small-PR

#20 Chore/set linter config
  .eslintrc.js
  components/Logo.vue
  components/modals/modalDeleteEnvironment.vue
  components/modals/modalEditEnvironment.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/environment.vue
  pages/home.vue
  pages/index.vue
  pages/mission.vue
  pages/new-mission.vue
  pages/signin.vue
  services/backend.service.js
  services/login.service.js
  store/empty.store.js
  store/index.js
  store/utils.js
  test/Logo.spec.js
  test/services/login.service.spec.js
Labels: Ready

#21 chore: set linter config
  .eslintrc.js
  components/modals/modalDeleteEnvironment.vue
  components/modals/modalEditEnvironment.vue
  nuxt.config.js
  pages/environment.vue
  pages/home.vue
  pages/index.vue
  pages/mission.vue
  pages/new-mission.vue
  pages/signin.vue
  services/backend.service.js
  services/login.service.js
  store/empty.store.js
  store/index.js
  store/utils.js
  test/services/login.service.spec.js
Labels: Ready

#23 Chore/notification toasted
  .babelrc
  components/formInput.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/index.vue
  pages/signin.vue
  plugins/toasted.js
  services/toast.service.js
  test/pages/index.spec.js
  test/services/login.service.spec.js
  test/testTemplate.js
  yarn.lock
Labels: Ready

#24 MEP
  .babelrc
  components/formInput.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/index.vue
  pages/signin.vue
  plugins/toasted.js
  services/toast.service.js
  test/pages/index.spec.js
  test/services/login.service.spec.js
  test/testTemplate.js
  yarn.lock
Labels: Ready

#26 test:add test unit for signin page
  pages/home.vue
  pages/signin.vue
  services/backend.service.js
  style/login_signin.css
  test/pages/signin.spec.js
Labels: Ready

#27 Chore/add e2 e tests
  .circleci/config.yml
  cypress.json
  cypress/videos/index.spec.js.mp4
  jest.config.js
  package-lock.json
  package.json
  test/e2e/.eslintrc.js
  test/e2e/integration/index.spec.js
  test/e2e/plugins/index.js
  test/e2e/support/command.js
  test/e2e/support/index.js
  test/unit/pages/index.spec.js
  test/unit/pages/signin.spec.js
  test/unit/services/login.service.spec.js
  yarn.lock
Labels: Ready

#29 test:add first e2e test
  cypress.json
  cypress/videos/index.spec.js.mp4
  package.json
  test/e2e/apiRoutes.js
  test/e2e/fixtures/account.json
  test/e2e/integration/index.spec.js
Labels: Ready

#30 MEP
  .circleci/config.yml
  cypress.json
  jest.config.js
  package-lock.json
  package.json
  pages/home.vue
  pages/signin.vue
  services/backend.service.js
  style/login_signin.css
  test/e2e/.eslintrc.js
  test/e2e/apiRoutes.js
  test/e2e/fixtures/account.json
  test/e2e/integration/index.spec.js
  test/e2e/plugins/index.js
  test/e2e/support/command.js
  test/e2e/support/index.js
  test/unit/pages/index.spec.js
  test/unit/pages/signin.spec.js
  test/unit/services/login.service.spec.js
  yarn.lock
Labels: Ready

#31 test: add test for signin page and update test for index page
  test/e2e/apiRoutes.js
  test/e2e/fixtures/account.json
  test/e2e/integration/index.spec.js
  test/e2e/integration/signin.spec.js
Labels: Ready
